const { FIXTURE_PERSON_ID, FIXTURE_ORG_UNIT_ID, FIXTURE_POSITION_ID } = require('../src/constants');
const { fakeChecksumPid } = require('../src/security/fakePid');

// รายการทุก operation ใน personnel-mdm-openapi.yaml (31 path, ตัดนับตาม method จริงคือ 34 operation)
// ใช้เดินทดสอบ contract แบบครอบคลุมทุกจุด - path/scope/body ต้องตรงกับสัญญาจริงในสเปกเสมอ
// (ห้ามแก้สเปกเพื่อให้ตรงกับ test - ถ้าไม่ตรงคือโค้ดผิด ไม่ใช่สเปกผิด)
const EMPLOYMENT_UPSERT_BODY = {
  employeeNo: 'EMP-TEST-001',
  personnelType: 'CIVIL_SERVANT',
  positionId: FIXTURE_POSITION_ID,
  orgUnitId: FIXTURE_ORG_UNIT_ID,
  effectiveFrom: '2024-01-01',
};

const operations = [
  { name: 'searchPersons', method: 'get', path: '/persons', scope: 'personnel:read:basic', expectStatus: 200 },
  {
    name: 'provisionPerson',
    method: 'post',
    path: '/persons',
    // HR จริงถือหลาย scope พร้อมกัน (personnel:read:basic เป็น scope ขั้นต่ำของทุก consumer ตาม §2.2)
    // ไม่ใช่แค่ scope เดียวที่ operation นี้ระบุไว้ขั้นต่ำ - Person response ต้องมี "basic" เสมอ
    scope: 'personnel:read:basic personnel:provision',
    body: {
      pid: fakeChecksumPid(),
      expectedFirstNameTh: 'ทดสอบ',
      expectedLastNameTh: 'ระบบ',
      employment: EMPLOYMENT_UPSERT_BODY,
    },
    expectStatus: 201,
  },
  {
    name: 'lookupPersonByPid',
    method: 'post',
    path: '/persons/lookup',
    scope: 'personnel:lookup:pid',
    body: { pid: fakeChecksumPid(), justification: 'ทดสอบเหตุผลการค้นหา personId จาก pid' },
    expectStatus: 200,
  },
  {
    name: 'getPerson',
    method: 'get',
    path: `/persons/${FIXTURE_PERSON_ID}`,
    scope: 'personnel:read:basic',
    expectStatus: 200,
  },
  {
    name: 'getPersonPhoto',
    method: 'get',
    path: `/persons/${FIXTURE_PERSON_ID}/photo`,
    scope: 'personnel:read:photo',
    expectStatus: 200,
    binary: true,
  },
  {
    name: 'getPersonPid',
    method: 'get',
    path: `/persons/${FIXTURE_PERSON_ID}/pid`,
    query: { justification: 'ทดสอบเหตุผลการถอดรหัสเลขบัตร' },
    scope: 'personnel:read:pid',
    expectStatus: 200,
  },
  {
    name: 'getEmployment',
    method: 'get',
    path: `/persons/${FIXTURE_PERSON_ID}/employment`,
    scope: 'personnel:read:employment',
    expectStatus: 200,
  },
  {
    name: 'upsertEmployment',
    method: 'put',
    path: `/persons/${FIXTURE_PERSON_ID}/employment`,
    scope: 'personnel:write:employment',
    body: EMPLOYMENT_UPSERT_BODY,
    expectStatus: 200,
  },
  {
    name: 'deactivatePerson',
    method: 'post',
    path: `/persons/${FIXTURE_PERSON_ID}/deactivate`,
    scope: 'personnel:read:basic personnel:write:employment',
    body: { employmentStatus: 'RESIGNED', separationDate: '2024-01-01' },
    expectStatus: 200,
  },
  {
    name: 'reactivatePerson',
    method: 'post',
    path: `/persons/${FIXTURE_PERSON_ID}/reactivate`,
    scope: 'personnel:read:basic personnel:write:employment',
    body: EMPLOYMENT_UPSERT_BODY,
    expectStatus: 200,
  },
  {
    name: 'requestReverify',
    method: 'post',
    path: `/persons/${FIXTURE_PERSON_ID}/reverify`,
    scope: 'personnel:write:employment',
    body: { reason: 'ทดสอบ' },
    expectStatus: 202,
  },
  {
    name: 'getPersonChangeLog',
    method: 'get',
    path: `/persons/${FIXTURE_PERSON_ID}/change-log`,
    scope: 'audit:read',
    expectStatus: 200,
  },
  { name: 'getMe', method: 'get', path: '/me', scope: 'personnel:self', personId: FIXTURE_PERSON_ID, expectStatus: 200 },
  {
    name: 'updateMyContact',
    method: 'put',
    path: '/me/contact',
    scope: 'personnel:self',
    personId: FIXTURE_PERSON_ID,
    body: { mobilePhone: '0812345678' },
    expectStatus: 200,
  },
  {
    name: 'replaceMyEmergencyContacts',
    method: 'put',
    path: '/me/emergency-contacts',
    scope: 'personnel:self',
    personId: FIXTURE_PERSON_ID,
    body: [{ fullName: 'ทดสอบ ผู้ติดต่อ', relationship: 'เพื่อน', phone: '0899999999', priority: 1 }],
    expectStatus: 200,
  },
  {
    name: 'reportIdentityIssue',
    method: 'post',
    path: '/me/report-identity-issue',
    scope: 'personnel:self',
    personId: FIXTURE_PERSON_ID,
    body: { fieldKey: 'identity.reg_address_text', description: 'ที่อยู่ไม่ตรงกับความเป็นจริง' },
    expectStatus: 202,
  },
  {
    name: 'listMyConsents',
    method: 'get',
    path: '/me/consents',
    scope: 'personnel:self',
    personId: FIXTURE_PERSON_ID,
    expectStatus: 200,
  },
  {
    name: 'setMyConsent',
    method: 'put',
    path: '/me/consents/DIRECTORY_PUBLISH',
    scope: 'personnel:self',
    personId: FIXTURE_PERSON_ID,
    body: { status: 'GRANTED', policyVersion: '2026-01-01' },
    expectStatus: 200,
  },
  {
    name: 'syncFromThaid',
    method: 'post',
    path: '/sync/thaid',
    scope: 'sync:thaid',
    body: {
      claims: { pid: fakeChecksumPid(), firstNameTh: 'ทดสอบ', lastNameTh: 'ระบบ' },
      context: { appId: 'eoffice', audience: 'PERSONNEL' },
    },
    expectStatus: 200,
  },
  {
    name: 'importEmploymentBatch',
    method: 'post',
    path: '/sync/hr/employment-batch',
    scope: 'personnel:import',
    body: { mode: 'DRY_RUN', rows: [] },
    expectStatus: 200,
  },
  {
    name: 'listClaimRequests',
    method: 'get',
    path: '/claim-requests',
    scope: 'personnel:provision',
    expectStatus: 200,
  },
  {
    name: 'resolveClaimRequest',
    method: 'post',
    path: '/claim-requests/33333333-3333-3333-3333-333333333333/resolve',
    scope: 'personnel:provision',
    body: { action: 'REJECT' },
    expectStatus: 200,
  },
  {
    name: 'listStalePersons',
    method: 'get',
    path: '/reverify/stale',
    scope: 'personnel:read:basic personnel:provision',
    expectStatus: 200,
  },
  { name: 'listEvents', method: 'get', path: '/events', scope: 'events:read', expectStatus: 200 },
  {
    name: 'listWebhookSubscriptions',
    method: 'get',
    path: '/webhooks/subscriptions',
    scope: 'webhook:manage',
    expectStatus: 200,
  },
  {
    name: 'createWebhookSubscription',
    method: 'post',
    path: '/webhooks/subscriptions',
    scope: 'webhook:manage',
    body: { url: 'https://example.lp-pao.go.th/hooks/mdm', eventTypes: ['PERSON_DEACTIVATED'] },
    expectStatus: 201,
  },
  {
    name: 'deleteWebhookSubscription',
    method: 'delete',
    path: '/webhooks/subscriptions/55555555-5555-5555-5555-555555555555',
    scope: 'webhook:manage',
    expectStatus: 204,
  },
  {
    name: 'testWebhookSubscription',
    method: 'post',
    path: '/webhooks/subscriptions/55555555-5555-5555-5555-555555555555/test',
    scope: 'webhook:manage',
    expectStatus: 200,
  },
  {
    name: 'listWebhookDeliveries',
    method: 'get',
    path: '/webhooks/deliveries',
    scope: 'webhook:manage',
    expectStatus: 200,
  },
  {
    name: 'retryWebhookDelivery',
    method: 'post',
    path: '/webhooks/deliveries/66666666-6666-6666-6666-666666666666/retry',
    scope: 'webhook:manage',
    expectStatus: 202,
  },
  { name: 'listOrgUnits', method: 'get', path: '/org-units', scope: 'personnel:read:basic', expectStatus: 200 },
  { name: 'listPositions', method: 'get', path: '/positions', scope: 'personnel:read:basic', expectStatus: 200 },
  {
    name: 'listAccessLogs',
    method: 'get',
    path: '/audit/access-logs',
    scope: 'audit:read',
    expectStatus: 200,
  },
  { name: 'health', method: 'get', path: '/health', noAuth: true, expectStatus: 200 },
];

module.exports = { operations };
